name: Build and Deploy Flask App to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust Python version as needed

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Flask app to generate static content (if any)
      - name: Run Flask Build (Optional)
        run: |
          echo "This step is used only if your app builds static files dynamically."

      # Step 5: Prepare the build directory for deployment
      - name: Prepare Static Build
        run: |
          mkdir build
          cp -r templates static build/
          cp app.py build/

      # Step 6: Upload Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: flask-build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download Artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: flask-build

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
